ProjectMau/trunk/ViewCallAPI/Models/ErrorViewModel.cs
namespace ViewCallAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectMau/trunk/ViewCallAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ViewCallAPI.Models;

namespace ViewCallAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectMau/trunk/ViewCallAPI/Controllers/ProductViewController.cs
using CoreLib.Entities;

using Microsoft.AspNetCore.Mvc;

using System.Text;
using static OfficeOpenXml.ExcelErrorValue;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace ViewCallAPI.Controllers
{
    public class ProductViewController : Controller
    {
      //  private ProductController productController;
         private readonly HttpClient _httpClient;

        public ProductViewController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAllCategory()
        {
            var response = await _httpClient.GetAsync("https://localhost:7029/api/Product/categories");


            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                // Trả về dữ liệu từ API
                return Content(content, "application/json");
            }
            else
            {
                return StatusCode((int)response.StatusCode); // Trả về mã lỗi tương ứng
            }
        }
        public async Task<IActionResult> DetailProduct(int Id)
        {

            var response = await _httpClient.GetAsync("https://localhost:7029/api/Product/detailproduct/" + Id);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                // Trả về dữ liệu từ API
                return Content(content, "application/json");
            }
            else
            {
                return StatusCode((int)response.StatusCode); // Trả về mã lỗi tương ứng
            }
        }

        public async Task<IActionResult> getAllProduct()
        {
            var response = await _httpClient.GetAsync("https://localhost:7029/api/Product/products");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                // Trả về dữ liệu từ API
                return Content(content, "application/json");
            }
            else
            {
                return StatusCode((int)response.StatusCode); // Trả về mã lỗi tương ứng
            }
        }
        public async Task<IActionResult> InsertProduct(Product product)
        {
            var productJson = JsonSerializer.Serialize(product);

            HttpContent values = new StringContent(productJson, Encoding.UTF8, "application/json");

            string apiUrl = "https://localhost:7029/api/Product/addproduct";

            var response = await _httpClient.PostAsync(apiUrl, values);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                // Trả về dữ liệu từ API
                return Content(content, "application/json");
            }
            else
            {
                return StatusCode((int)response.StatusCode); // Trả về mã lỗi tương ứng
            }
        }


        public async Task<IActionResult> UpdateProduct(Product product, int id)
        {
            var productJson = JsonSerializer.Serialize(product);

            HttpContent values = new StringContent(productJson, Encoding.UTF8, "application/json");

            string apiUrl = "https://localhost:7029/api/Product/updateproduct/"+id;

            var response = await _httpClient.PutAsync(apiUrl, values);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                // Trả về dữ liệu từ API
                return Content(content, "application/json");
            }
            else
            {
                return StatusCode((int)response.StatusCode); // Trả về mã lỗi tương ứng
            }

        }

        public async Task<IActionResult> DeleteProduct(int Id)
        {

            string apiUrl = "https://localhost:7029/api/Product/deleteproduct/" + Id;

            var response = await _httpClient.DeleteAsync(apiUrl);

            var responseString = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();

                // Trả về dữ liệu từ API
                return Content(content, "application/json");
            }
            else
            {
                return StatusCode((int)response.StatusCode); // Trả về mã lỗi tương ứng
            }

        }
    }
}

ProjectMau/trunk/ViewCallAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectMau/trunk/ViewCallAPI/Views/ProductView/Index.cshtml
@model CoreLib.Entities.Product;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <form method="post" id="ProductForm">
        <div class="col-8">
            <h4>Product manager</h4>
            <hr class="bg-danger border-2 border-top border-danger mt-4" />
            <div class="form-floating mb-3">
                <input type="text"
                       class="form-control thongtin rounded-4"
                       id="txtProductName" 
                       name="productName"
                       asp-for="ProductName"
                       placeholder="name" />
                <label for="floatingInput">Name</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text"
                       class="form-control thongtin rounded-4"
                       id="txtDescription"
                       name="description"
                       asp-for="Description"
                       placeholder="description" />
                <label for="floatingInput">Description</label>
            </div>
            <div class="form-floating mb-3">
                <input type="text"
                       class="form-control thongtin rounded-4"
                       id="txtQuantity"
                       name="quantity"
                       asp-for="Quantity"
                       placeholder="Quantity" />
                <label for="floatingInput">Number in Stock</label>
            </div>
            <div class="form-floating mb-3">
                <select class="form-select thongtin"
                        id="cboIdCategory"
                        asp-for="IdCategory"
                        name="idCategory"
                        aria-label="Floating label select example"></select>
                <!-- <input
                  class="form-control thongtin rounded-4"
                  id="txtIdCategory"
                  placeholder="Category"
                  asp-for="product.IdCategory"
                /> -->
                <label for="floatingSelect">Category</label>
            </div>

            <button type="button"
                    class="btn btn-outline-secondary mb-3"
                    id="btnSave">
                Save
            </button>
            <button type="button"
                    class="btn btn-outline-secondary mb-3"
                    id="btnUpdate">
                Update
            </button>
        </div>
    </form>

    <table class="table table-striped" id="datatable">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Description</th>
                <th scope="col">Category</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<script src="/assets/vendors/general/popper.js/dist/umd/popper.js"
        type="text/javascript"></script>
<script src="/assets/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.js"
        type="text/javascript"></script>
<script src="/assets/vendors/general/sticky-js/dist/sticky.min.js"
        type="text/javascript"></script>
<script src="/assets/vendors/general/jquery/dist/jquery.min.js"
        type="text/javascript"></script>
<script src="/assets/demo/demo3/base/scripts.bundle.min.js"
        type="text/javascript"></script>
<script src="/js/jquery-ajax-native.js"></script>
<script src="/assets/vendors/custom/datatables/datatables.bundle.min.js"
        type="text/javascript"></script>
<script src="/assets/vendors/general/sweetalert2/dist/sweetalert2.js"
        type="text/javascript"></script>

<script src="/js/site.js"></script>
<script>
    var id = -1;
    var dataTable = null; // Biến để lưu trữ đối tượng DataTable

    $.fn.serializeObject = function () {
        var o = {};
        var a = this.serializeArray();
        $.each(a, function () {
            if (o[this.name]) {
                if (!o[this.name].push) {
                    o[this.name] = [o[this.name]];
                }
                o[this.name].push(this.value || "");
            } else {
                o[this.name] = this.value || "";
            }
        });
        return o;
    };
//    var url = "https://localhost:7029/api/Product";
    //// Hàm để reload lại toàn bộ DataTable
    function reloadDataTable() {
        dataTable.destroy();
        getAll();
    }
    $("#btnSave").click(function () {
        let formData = new FormData($('form')[0]);
        //var formData = $("form").serializeObject();
        //var jsonData = JSON.stringify(formData);

        //console.log(jsonData);
        //Hiển thị ảnh loadding
        $("#loading").addClass("loading");
        $.ajax('@Url.Action("InsertProduct", "ProductView")', {
            type: "post",
            processData: false,
            contentType: false,
         //   contentType: "application/json",
            data: formData,
        })
            .done(function (data) {
                // data.code : 0 - Không có lỗi trả về
                displayResponse(data) // Hiện thị popup thông báo kết quả
                    .then(function () {
                        // Thực hiện các hàm sau khi thông báo được đóng
                        if (data.code == 0) {
                            resetform(); // Reset Form dữ liệu
                            reloadDataTable(); // Reload DataTable
                        }
                    });
            })
            .fail(function () {
                showError("Có lỗi xảy ra");
            });
        id = -1;
        //Xóa ảnh loading
        $("#loading").removeClass("loading");
        //$('.nav-item a[href="#k_tabs_1"]').tab("show");
    });

    $("#btnUpdate").click(function () {
        if (id == -1) {
            showError("Chưa chọn sản phẩm cần sửa");
            return;
        }
        let formData = new FormData($('form')[0]);

       // console.log(jsonData);
        //Hiển thị ảnh loadding
        $("#loading").addClass("loading");
        $.ajax('@Url.Action("UpdateProduct", "ProductView")' + "?Id=" + id, {
            type: "post",
            processData: false,
            contentType: false,
            //   contentType: "application/json",
            data: formData,
        })
            .done(function (data) {
                //data.code : 0 - Không có lỗi trả về
                displayResponse(data) // Hiện thị popup thông báo kết quả
                    .then(function () {
                        // Thực hiện các hàm sau khi thông báo được đóng
                        if (data.code == 0) {
                            resetform(); // Reset Form dữ liệu
                            reloadDataTable(); // Reload DataTable
                        }
                    });
            })
            .fail(function () {
                showError("Có lỗi xảy ra");
            });
        //Xóa ảnh loading
        id = -1;
        $("#loading").removeClass("loading");
        $('.nav-item a[href="#k_tabs_1"]').tab("show");
    });

    $("#datatable").on("click", ".button-delete", function () {
        var value = $(this).val();
        //    //Hiển thị ảnh loadding
        $("#loading").addClass("loading");
        $.ajax('@Url.Action("DeleteProduct", "ProductView")'+"?Id=" + value)
            .done(function (data) {
                //data.code : 0 - Không có lỗi trả về
                displayResponse(data) // Hiện thị popup thông báo kết quả
                    .then(function () {
                        // Thực hiện các hàm sau khi thông báo được đóng
                        if (data.code == 0) {
                            resetform(); // Reset Form dữ liệu
                            reloadDataTable(); // Reload DataTable
                        }
                    });
            })
            .fail(function () {
                showError("Có lỗi xảy ra");
            });
        //Xóa ảnh loading
        $("#loading").removeClass("loading");
        $('.nav-item a[href="#k_tabs_1"]').tab("show");
        id = -1;

        // Thực hiện các thao tác xử lý cho button 1
    });
    $("#datatable").on("click", ".button-detail", function () {
        var value = $(this).val();
        id = value;
        //    //Hiển thị ảnh loadding
        //$('#loading').addClass('loading');
        $.ajax('@Url.Action("DetailProduct", "ProductView")' + "?Id=" + value)
            .done(function (data) {
                var product = data;
                console.log(data);
                $("#txtProductName").val(product.productName);
                $("#txtDescription").val(product.description);
                $("#txtQuantity").val(product.quantity);
                $("#cboIdCategory").val(product.idCategory);
            })
            .fail(function () {
                showError("Có lỗi xảy ra");
            });
    });
    function resetform() {
        $("#ProductForm").trigger("reset");
    }
    function showSelectCategories() {
        $.get('@Url.Action("GetAllCategory", "ProductView")').done(function (response) {
            var tableBody = $("#cboIdCategory");
            tableBody.empty();
            var html = "";
            var list = response;
            for (var i = 0; i < list.length; i++) {
                html += `
                                                 <option value="${list[i].id}">${list[i].categoryName}</option>
                                                `;
            }
            tableBody.append(html);
        });
    }

    function getAll() {
        var ProductName = "";
        $.get('@Url.Action("getAllProduct", "ProductView")').done(function (response) {
            console.log(response);
            dataTable = $("#datatable").DataTable({
                data: response, // Dữ liệu trả về từ server
                columns: [
                    { data: "id" },
                    { data: "productName" },
                    { data: "quantity" },
                    { data: "description" },
                    { data: "categoryName" },
                    {
                        data: "id",
                        title: "Hành động",
                        render: function (data, type, row) {
                            return (
                                `
                                                                    <button type="button" value="` +
                                data +
                                `" class="btn btn-outline-primary button-detail">Detail</button>
                                                                            <button type="button" value="` +
                                data +
                                `" class="btn btn-outline-primary button-delete">Delete</button>
                                                    `
                            );
                        },
                    },
                ],
            });
        });
    }
    getAll();
    showSelectCategories();
</script>

ProjectMau/trunk/ViewCallAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<!-- begin::Head -->
<head>

    <meta charset="utf-8" />
    <meta name="description" content="EzSearch Internal">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="shortcut icon" href="~/favicon.png">
    <!--begin::Web font -->
    <!--end::Web font -->
    <!--begin::Page Vendors Styles -->
    <!--data table style sheet -->
    <link href="~/assets/vendors/custom/datatables/datatables.bundle.min.css" rel="stylesheet" type="text/css">

    <link href="~/assets/demo/demo3/base/style.bundle.css" rel="stylesheet" type="text/css" />
    <!--end::Page Vendors Styles -->
    <!--begin:: Global Mandatory Vendors -->
    <link href="~/assets/vendors/general/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" type="text/css" />
    <!--end:: Global Mandatory Vendors -->
    <!--begin:: Global Optional Vendors -->

    <script src="~/js/polyfill.min.js" type="text/javascript"></script>
    <script src="~/assets/vendors/general/jquery/dist/jquery.min.js" type="text/javascript"></script>

    <link href="~/assets/vendors/general/select2/css/select2.min.css" rel="stylesheet" />
    <script src="~/assets/vendors/general/select2/js/select2.min.js"></script>

    @*HienDV*@
    @* Escape < , > Html charaters in response to prevent XSS *@
    <script>
        const encodeHtmlString = function (rawString) {
            return rawString.replace(/[<>\&]/gim,
                function (i) {
                    return '&#' + i.charCodeAt(0) + ';';
                });
        }
        $.ajaxSetup({
            converters: {
                "text json": function (data) {
                    return JSON.parse(encodeHtmlString(data));
                }
            }
        });
    </script>

    <link href="~/assets/vendors/custom/vendors/line-awesome/css/line-awesome.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendors/general/animate.css/animate.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendors/general/toastr/build/toastr.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendors/custom/vendors/fontawesome5/css/all.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/vendors/general/sweetalert2/dist/sweetalert2.css" rel="stylesheet" type="text/css">
    <link href="~/css/Customer.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!--end:: Global Optional Vendors -->
    @* <link rel="shortcut icon" href="~/assets/media/logos/favicon.ico" /> *@
    <style>
        .dataTables_length {
            text-align: left;
        }
    </style>
    <title>@ViewData["Title"] - TrainningDotNetCore</title>
</head>


<!-- end::Head -->
<!-- begin::Body -->
<body class="k-page--loading-enabled k-page--loading k-page--fixed k-header--fixed k-header--minimize-menu k-header-mobile--fixed" style="background-color: white">

    <!-- begin::Page loader -->
    <!-- end::Page Loader -->
    <!-- begin:: Page -->
    <!-- begin:: Header Mobile -->

    <div id="k_header_mobile" class="k-header-mobile">
        <div class="fpts-header">
            <div class="container d-flex ">
                <div class="fpts-left">
                </div>
                <div class="fpts-right d-flex justify-content-end align-items-center">
                    @* <a class="fpts-language" href="/?culture=en"><img src="~/images/icon/lang-icon-EN.png"></a> *@
                </div>
            </div>
        </div>
        <div class="k-header-mobile-bottom">
            <div class="k-header-mobile__toolbar">
                <button class="k-header-mobile__toolbar-toggler" id="k_header_mobile_toggler"><span></span></button>
            </div>
            <div class="k-header-mobile__logo">
                <a href="/">
                    <img alt="Logo" src="~/assets/media/logos/FPTS.png" />
                </a>
            </div>

            <div class="header-info d-flex align-items-center p-2">
                <a class="mx-2" href="https://accounts.fpts.com.vn/Contact"><img src="~/images/icon/icon-message.png" /></a>
                <a><img src="~/images/icon/icon-user.png" alt="User" /></a>
            </div>
        </div>

    </div>

    <!-- end:: Header Mobile -->
    <div class="k-grid k-grid--hor k-grid--root">
        <div class="k-grid__item k-grid__item--fluid k-grid k-grid--ver k-page">
            <div class="k-grid__item k-grid__item--fluid k-grid k-grid--hor k-wrapper " id="k_wrapper">

                <!-- begin:: Header -->
                <div id="k_header" class="k-header k-grid__item  k-header--fixed " data-kheader-minimize="on" style="background: linear-gradient(45deg, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 1) 12%, rgba(52, 152, 219, 1) 43%)">
                    <div class="fpts-header">
                        <div class="container d-flex ">
                            <div class="fpts-left">
                            </div>
                            <div class="fpts-right d-flex justify-content-end align-items-center">
                                @* <a class="fpts-language" href="/?culture=en"><img src="~/images/icon/lang-icon-EN.png"></a> *@
                                <span class="mx-3 text-light">  Admin</span>
                                <a class="text-light" href="@Url.Action("Logout","Login")"><i class="fas fa-sign-out-alt"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="k-header__bottom">
                        <div class="k-container">

                            <!-- begin: Header Menu -->
                            <button class="k-header-menu-wrapper-close" id="k_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
                            <div class="k-header-menu-wrapper" id="k_header_menu_wrapper">
                                <div id="k_header_menu" class="k-header-menu k-header-menu-mobile ">
                                    <ul class="k-menu__nav ">
                                        @* Thông tin đại hội *@

                                        <li class="k-menu__item  k-menu__item--submenu k-menu__item--rel ttdh " data-kmenu-submenu-toggle="click" aria-haspopup="true" style="padding-left: 0!important">
                                            <a class="k-menu__link k-menu__toggle">
                                                <span class="k-menu__link-text" id="menu_ttdh">Trang chủ</span>
                                                <!--<i class="k-menu__hor-arrow la la-angle-down"></i><i class="k-menu__ver-arrow la la-angle-right"></i>-->
                                            </a>
                                        </li>
                                        <li class="k-menu__item  k-menu__item--submenu k-menu__item--rel ttdh bdlinh" data-kmenu-submenu-toggle="click" aria-haspopup="true" style="padding-left: 0!important">
                                            <a class="k-menu__link k-menu__toggle">
                                                <span class="k-menu__link-text" id="menu_ttdh">Danh mục tin</span>
                                                <!--<i class="k-menu__hor-arrow la la-angle-down"></i><i class="k-menu__ver-arrow la la-angle-right"></i>-->
                                            </a>
                                            <div class="k-menu__submenu k-menu__submenu--classic k-menu__submenu--left ttdh__submenu">
                                                <div class="triangle"></div>
                                                <ul class="k-menu__subnav">
                                                    <div class="k-menu__subnav-half" style="float:left;">
                                                    <li class="k-menu__item " aria-haspopup="true">
                                                        <a class="k-menu__link " href="@Url.Action("Index", "Catalogs")">
                                                            <!--<i class="k-menu__link-bullet k-menu__link-bullet--dot"><span></span></i>-->
                                                            <span class="k-menu__link-text">Danh mục tin</span>
                                                        </a>
                                                    </li>
                                            </div>
                                    </ul>
                                </div>
                                </li>
                                </ul>
                            </div>
                            <div class="k-header-toolbar">
                            </div>
                        </div>

                        <!-- end: Header Menu -->
                    </div>
                </div>
            </div>
            <div class="title_line d-flex">
                <div class="container">
                    <span class="title_line_item">
                        <font color="#000"><a href="@Url.Action("Index", "Home")" style="color:#000;">Home</a></font>
                    </span>
                    <span class="title_line_item">
                        <i class="fa  fa-caret-right"></i>
                    </span>

                </div>
            </div>
            <!-- end:: Header -->
            <div class="k-grid__item k-grid__item--fluid k-grid k-grid--ver k-grid--stretch" style="background-color: white;">
                <div class="k-container k-content-wrapper  k-grid k-grid--ver" id="k_content_wrapper">

                    <!-- begin:: Content -->
                    <div class="k-content	k-grid__item k-grid__item--fluid k-grid k-grid--hor DaiHoiform" id="k_content">
                            @RenderBody()
                    </div>
                </div>
            </div>

            <!-- begin:: Footer -->
            <div class="k-footer k-grid__item" id="k_footer">

                <div class="fpts-securities">
                    <div class="k-container">
                        <p>© 2020 Công ty cổ phần chứng khoán FPT</p>
                    </div>
                </div>
            </div>

            <!-- end:: Footer -->
        </div>
    </div>
    </div>

    <!-- begin::Scrolltop -->
    <div id="k_scrolltop" class="k-scrolltop">
        <i class="la la-arrow-up"></i>
    </div>
    <!-- end::Scrolltop -->
    <!-- begin::Global Config -->
    <script>
        var KAppOptions = {
            "colors": {
                "state": {
                    "brand": "#4d5cf2",
                    "metal": "#c4c5d6",
                    "light": "#ffffff",
                    "accent": "#00c5dc",
                    "primary": "#5867dd",
                    "success": "#34bfa3",
                    "info": "#36a3f7",
                    "warning": "#ffb822",
                    "danger": "#fd3995",
                    "focus": "#9816f4"
                },
                "base": {
                    "label": ["#c5cbe3", "#a1a8c3", "#3d4465", "#3e4466"],
                    "shape": ["#f0f3ff", "#d9dffa", "#afb4d4", "#646c9a"]
                }
            }
        };
    </script>


    <script src="~/assets/vendors/general/popper.js/dist/umd/popper.js" type="text/javascript"></script>
    <script src="~/assets/vendors/general/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/assets/vendors/general/perfect-scrollbar/dist/perfect-scrollbar.js" type="text/javascript"></script>
    <script src="~/assets/vendors/general/sticky-js/dist/sticky.min.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
    <!--Sử dụng cho JS SaveFile, Xuất báo cáo-->
    <script src="~/lib/filesaver/FileSaver.min.js"></script>
    <script src="~/js/jquery-ajax-native.js"></script>
    <!--<script src="~/js/jReport.js"></script>-->

    <script src="~/assets/demo/demo3/base/scripts.bundle.min.js" type="text/javascript"></script>

    <script src="~/assets/vendors/custom/datatables/datatables.bundle.min.js" type="text/javascript"></script>
    <script src="~/assets/vendors/general/sweetalert2/dist/sweetalert2.js" type="text/javascript"></script>
    <script src="~/js/site.js"></script>


</body>
<!--end:: Body-->
</html>